"use strict";
// Future versions of Hyper may add additional config options,
// which will not automatically be merged into this file.
// See https://hyper.is#cfg for all currently supported options.
module.exports = {
    config: {
        updateChannel: 'stable',
        fontSize: 12,
        fontFamily: 'FiraCode Nerd Font Mono',
        fontWeight: 'normal',
        fontWeightBold: 'bold',
        lineHeight: 1,
        letterSpacing: 0,
        cursorColor: 'rgba(248,28,229,0.8)',
        cursorAccentColor: '#000',
        cursorShape: 'BLOCK',
        cursorBlink: true,
        foregroundColor: '#fff',
        backgroundColor: '#262721',
        selectionColor: '#48473D',
        borderColor: '#262721',
        css: '',
        termCSS: '',
        workingDirectory: '',
        showHamburgerMenu: '',
        showWindowControls: '',
        padding: '10px',
        colors: {
            black: '#000000',
            red: '#C51E14',
            green: '#1DC121',
            yellow: '#C7C329',
            blue: '#65D9EE',
            magenta: '#F82A71',
            cyan: '#A1EEE4',
            white: '#C7C7C7',
            lightBlack: '#686868',
            lightRed: '#FD6F6B',
            lightGreen: '#67F86F',
            lightYellow: '#FFFA72',
            lightBlue: '#65D9EE',
            lightMagenta: '#F82A71',
            lightCyan: '#A1EEE4',
            lightWhite: '#FFFFFF',
            limeGreen: '#32CD32',
            lightCoral: '#F08080',
        },
        shell: '',
        shellArgs: ['--login'],
        env: {},
        bell: false,
        copyOnSelect: false,
        defaultSSHApp: true,
        quickEdit: false,
        macOptionSelectionMode: 'vertical',
        webGLRenderer: true,
        webLinksActivationKey: '',
        disableLigatures: true,
        disableAutoUpdates: false,
        screenReaderMode: false,
        preserveCWD: true,
    },
    plugins: [
        'hyper-search',
        'hyper-tabs-enhanced',
        'hyper-pane',
        'hyper-highlight-active-pane',
    ],
    localPlugins: [],
    keymaps: {},
};
//# sourceMappingURL=config-default.js.map
